### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gfox1984** [spiehdid/react-mixpanel-provider-component#2]
First of all, thanks for creating this package. The useMixPanel hook is exactly what I was after.

I'm having the following issue when running my app though, after adding the MixPanelProvider:

> C:\myapp\node_modules\react-mixpanel-provider-component\lib\index.js:12
> import React, { createContext, useContext, useEffect } from 'react';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at wrapSafe (internal/modules/cjs/loader.js:979:16)
>     at Module._compile (internal/modules/cjs/loader.js:1027:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.react-mixpanel-provider-component (C:\myapp\.next\server\pages\_app.js:441:18)
>     at __webpack_require__ (C:\myapp\.next\server\pages\_app.js:23:31)
>     at Module../src/pages/_app.tsx (C:\myapp\.next\server\pages\_app.js:310:91)
>     at __webpack_require__ (C:\myapp\.next\server\pages\_app.js:23:31)
>     at Object.0 (C:\myapp\.next\server\pages\_app.js:385:18)
>     at __webpack_require__ (C:\myapp\.next\server\pages\_app.js:23:31)
>     at C:\myapp\.next\server\pages\_app.js:91:18
>     at Object.<anonymous> (C:\myapp\.next\server\pages\_app.js:94:10)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)

Notes: 

- if I copy / paste your sources to my project, I don't have the error
- it's a Next.js app (but I don't think it's relevant)

**Comment by spiehdid** [comment]
@gfox1984 Please update the library to version 2.0.0. Then write what the result is.

**Comment by gfox1984** [comment]
That eliminated this error, thanks. 

However when I try to use Mixpanel on my page using this code:

```
  const { mixpanel } = useMixPanel();

  useEffect(() => {
    mixpanel.track('logged to site');
  }, []);
```

I have this error: "TypeError: Cannot read property 'track' of undefined"
![image](https://user-images.githubusercontent.com/14998184/107638604-1a669700-6c70-11eb-908b-4dff40765bd9.png)

**Comment by spiehdid** [comment]
@gfox1984 Have you initialized your mixpanel?

**Comment by gfox1984** [comment]
Yeah I have this in the app:

```
return (
    <MixPanelProvider
      token="xxxxx"
    >
        <Component {...pageProps} />
    </MixPanelProvider>
  );
```
NOTE: I did not have this issue when I copied the sources from this repo locally

**Comment by spiehdid** [comment]
@gfox1984 Have you transferred your token?

**Comment by gfox1984** [comment]
Sorry for the delay, I'd have to confirm the issue is not on my side (although it could be) by re-creating a new empty app and reproduce it. I might do it eventually, but I've been busy lately. You may consider closing the issue as it's not related to the original one anyway.
